### ISSUE TITLE
Deleting images

### ISSUE THREAD

**Issue by dropfen** [smeevil/cloudex#12]
Hey, this package looks great so far, are there any plans to include `Cloudex.delete(public_id)` ?

**Comment by smeevil** [comment]
Hi,

That's a fair point :) I'm currently in the middle of moving houses, so might take a bit before I've some time to look at it.  @manukall do you have any suggestions on adding more missing calls ? If so, I'll add those as well.

Gerard.

**Comment by manukall** [comment]
@smeevil thanks again for keeping me involved. I'm on holiday right now,
though, and my company isn't using cloudinary anymore. So I probably won't
be of much help.

**Comment by smeevil** [comment]
@manukall Then let me grab this opportunity to thank you for all the recent updates you have done on Cloudex, really appreciated ! Have a nice vacation and hope to run into you once again :)

**Comment by smeevil** [comment]
@dropfen thanks to @pauloancheta you can now use Cloudex.delete/1 :)
