### ISSUE TITLE
Version leniency

### ISSUE THREAD

**Issue by Tyler-pierce** [smeevil/cloudex#16]
Since you mention Phoenix support thought I'd ask if there's room for leniency on the poison and timex dependencies.  Phoenix 1.2.1 has a hard limit that is lower which is going to be fixed for poison on their next release but doesn't look like timex.  I got around it without a problem like so:

```
{:timex, "~> 3.1.0", override: true},
{:poison, "~> 3.0.0", override: true},
{:timex_ecto, "~> 3.1.0", override: true}, # required for timex v3+
```

If you don't feel that's an issue feel free to close this of course

**Comment by smeevil** [comment]
Hi,

I'm not quite sure if this is indeed a problem or not. The overrides you use are actually ment to solve this indeed. What would you suggest to set as versions otherwise ?

**Comment by abitdodgy** [comment]
I have a similar issue here:

```
Failed to use "httpoison" (version 0.10.0) because
  bamboo (version 0.7.0) requires ~> 0.9
  cloudex (versions 0.1.10 to 0.1.12) requires ~> 0.9.0
  mix.lock specifies 0.10.0

Failed to use "httpoison" (version 0.10.0) because
  bamboo (version 0.7.0) requires ~> 0.9
  cloudex (versions 0.1.13 and 0.1.14) requires ~> 0.11.0
  mix.lock specifies 0.10.0
```

**Comment by Tyler-pierce** [comment]
I think it's not a bug, just something that there may be an opportunity to make work a little more nicely in some circumstance.  I'm going to try two things 1) figure out which version of cloudex works out of the box with current phoenix (so it could be added to the docs where it lists phoenix support) and 2) see if I can add some or clauses or something to the dependencies and if the unit tests pass submit a PR.

abitdodgy, I suspect you could use a similar technique I did and work backwards through the dependencies, or just see if an earlier version of cloudex works for you for now

**Comment by smeevil** [comment]
Thank you @Tyler-pierce for pursuing this ;)
As far as I can think of, the only real culprit might be poison, which basically should work from any version for cloudex. The same for timex as I only use it for a current timestamp.

**Comment by smeevil** [comment]
Hi,

Is this still an issue or can it be closed ?

**Comment by Tyler-pierce** [comment]
Hello, I don't think it should me marked as an issue after all, can close yep. Most people should be able to override any issue in their mix file.  For my env I couldn't get that to work so forked and tried out toning back the version, which worked.  But I think that was my own fault and didn't think its worth a PR.

This worked for me in a Phoenix project in case it's of interest:
{:httpoison, "~> 0.9.0 or ~> 0.9.2"},
{:poison, "~> 1.5.0 or 2.1.0"},
{:timex, "~> 2.1.0 or 2.2.1"},

Apologies for not following up earlier

**Comment by smeevil** [comment]
NP :)
