### ISSUE TITLE
Uploading images via Plug.Upload path

### ISSUE THREAD

**Issue by seanwash** [smeevil/cloudex#25]
Hey all,

I'm unable to upload images from a Plug.Upload struct coming from a multipart form. The error I'm getting is `{:error, {:invalid, "<"}}` when using the live api, and `[error: {:invalid, "<"}]` when using `Cloudex.upload`.  Is uploading via Plug.Upload supported or do I need to do something like send it to S3 first and then use that URL?

**Comment by valo** [comment]
I saw the same error, but after doing `mix deps.uplock --all` and then `mix deps.get` it went away (warning: this might introduce regressions in your app as it will update all dependencies to the latest versions). Seems like some of the dependencies need to be updated or something. May be `poison` or `httpotion`. The versions that work for me are:

* poison, 3.1.0
* httpoison, 0.11.2
* timex, 3.1.13
* tzdata, 0.5.12

**Comment by smeevil** [comment]
Hi,

Sorry for the late reaction, I missed the email notification.
Is this still an issue or can it be closed ?

Gerard

**Comment by seanwash** [comment]
Hey @smeevil, I haven't had a chance to test this out yet, but I will be getting back to this this week. We can close it and I can reopen if its still an issue.

Thanks for the insight @valo!

**Comment by smeevil** [comment]
Great :)

**Comment by siegfried** [comment]
I'm getting the same error when I upload local files. Uploading via URL works fine.

* poison, 2.2.0
* httpoison, 0.9.2
* timex, 3.0.8
* tzdata, 0.5.12

Here is the VCR JSON file I got when it went wrong:

```json
[
  {
    "request": {
      "body": "{:multipart, [{\"api_key\", \"345661626337471\"}, {\"signature\", \"6866352a6a830c94a0898d2b5eafe8572969db8f\"}, {\"timestamp\", \"1498581590\"}, {:file, \"test/assets/example.png\"}]}",
      "headers": {
        "Content-Type": "application/x-www-form-urlencoded",
        "Accept": "application/json"
      },
      "method": "post",
      "options": [],
      "request_body": "",
      "url": "http://api.cloudinary.com/v1_1/dyb6wlcll/image/upload"
    },
    "response": {
      "body": "<h2>Incomplete response received from application</h2>",
      "headers": {
        "cache-control": "no-cache, no-store, must-revalidate",
        "Content-Type": "text/html; charset=UTF-8",
        "Date": "Tue, 27 Jun 2017 16:39:51 +0000",
        "Server": "cloudinary",
        "Status": "502 Bad Gateway",
        "Content-Length": "54",
        "Connection": "keep-alive"
      },
      "status_code": 502,
      "type": "ok"
    }
  }
]
```

By the way, one of my old project which worked fine can no longer upload local files as well. Here is the VCR JSON in the past:

```json
[
  {
    "request": {
      "body": "{:multipart, [{\"api_key\", \"345661626337471\"}, {\"signature\", \"2e1f41588b5d260d1d9bdb9d96bfb9b43ef36367\"}, {\"timestamp\", \"1478721780\"}, {:file, \"test/assets/example.png\"}]}",
      "headers": {
        "Content-Type": "application/x-www-form-urlencoded",
        "Accept": "application/json"
      },
      "method": "post",
      "options": [],
      "request_body": "",
      "url": "http://api.cloudinary.com/v1_1/dyb6wlcll/image/upload"
    },
    "response": {
      "body": "{\"public_id\":\"vnsogcgcn0xvompdllcn\",\"version\":1478721781,\"signature\":\"ee1c4c55995477004c761f65187cd04a5bf9c5ce\",\"width\":100,\"height\":100,\"format\":\"png\",\"resource_type\":\"image\",\"created_at\":\"2016-11-09T20:03:01Z\",\"tags\":[],\"bytes\":151,\"type\":\"upload\",\"etag\":\"aa12dd75aee7ccca65d670297295ef03\",\"url\":\"http://res.cloudinary.com/dyb6wlcll/image/upload/v1478721781/vnsogcgcn0xvompdllcn.png\",\"secure_url\":\"https://res.cloudinary.com/dyb6wlcll/image/upload/v1478721781/vnsogcgcn0xvompdllcn.png\",\"original_filename\":\"example\"}",
      "headers": {
        "Cache-Control": "max-age=0, private, must-revalidate",
        "Content-Type": "application/json; charset=utf-8",
        "Date": "Wed, 09 Nov 2016 20:03:01 GMT",
        "ETag": "\"5b1f2c7ec3479ebb05a5fbf5123bfe71\"",
        "Server": "cloudinary",
        "Status": "200 OK",
        "X-Request-Id": "8f4154fec22ae900",
        "X-UA-Compatible": "IE=Edge,chrome=1",
        "Content-Length": "518",
        "Connection": "keep-alive"
      },
      "status_code": 200,
      "type": "ok"
    }
  }
]
```

**Comment by siegfried** [comment]
The request body confuses me a lot. Isn't it supposed to contain the [file content](http://cloudinary.com/documentation/upload_images#uploading_with_a_direct_call_to_the_api) instead of (local) file path in it?

**Comment by jnmandal** [comment]
For posterity: I was trying to debug an error from cloudinary like this. It turns out I had a bad content-type in my request header. Hopefully thats helpful for somebody in the future.
