### ISSUE TITLE
Add 'moderation' to struct

### ISSUE THREAD

**Issue by gccoding** [smeevil/cloudex#37]
To support image moderation, could you please add 'moderation' type in lib/cloudex/uploaded_image.ex 

`moderation: [String.t] | [] | nil,`

https://cloudinary.com/documentation/aws_rekognition_ai_moderation_addon#moderation_response

Thank you very much!

**Comment by smeevil** [comment]
Sorry for the long response time, I just saw the open issue o.O

It has been added and 1.1.1 is now published :)
