### ISSUE TITLE
Support for videos

### ISSUE THREAD

**Issue by suranyami** [smeevil/cloudex#45]
Cloudinary has support for video uploads by passing the parameter `"resource_type" => "video".

This requires a different URL for the POST request:

https://api.cloudinary.com/v1_1/<cloud_name>/video/upload

I'm in the process of adding this in our fork, and will push a PR as soon as there is a working version.

**Comment by suranyami** [comment]
@smeevil We've got a tentative first step on this branch here:

https://github.com/visual-amplifiers/cloudex/tree/feature/video-upload

Unfortunately, it's failing when signing the request. We get this error:

```elixir
  1) test upload single video file (CloudexTest)
     test/cloudex/cloudex_test.exs:23
     match (=) failed
     code:  assert {:ok, %Cloudex.UploadedImage{}} = Cloudex.upload("test/assets/teamwork.mp4", %{resource_type: "video"})
     right: {:error,
             "Invalid Signature 3b51489e06ec14993a64635f9fe30636696314f8. String to sign - 'timestamp=1535005387'."}
     stacktrace:
       test/cloudex/cloudex_test.exs:25: (test)
```

Have you encountered this before? I've gone through the documentation and read through the `cloudinary_gem` ruby code, but I'm none the wiser. Current guess is that there are parameters that need to be added to the signature for video uploads specifically, but we can't seem to track down which ones.

**Comment by suranyami** [comment]
Also: was able to re-record the `exvcr` cassettes, but it was a bit klutzy: used my own credentials, then did a multi-file search/replace on `api_key`, `cloud_name`, `secret` to make them generic.

Is there a way we could automate that?

**Comment by suranyami** [comment]
This is fixed in the PR referenced above, @smeevil

**Comment by smeevil** [comment]
\o/ merged updated and published
