### ISSUE TITLE
Signature includes `resource_type`

### ISSUE THREAD

**Issue by erikreedstrom** [smeevil/cloudex#50]
According to the documentation, `resource_type` should not be included in the signature.

> All parameters added to the method call should be included except: `file`, **`resource_type`** and your `api_key`.

https://cloudinary.com/documentation/upload_images#generating_authentication_signatures

However, currently the API only removes `:file` from the data in `sign/1`.

**Comment by smeevil** [comment]
version 1.2.3 has been published, thanks for your time 👍
